name: Update Qiita Articles

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時に実行
  workflow_dispatch: # 手動で実行も可能

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}  # ここを追加
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: pip install requests

      - name: Fetch Qiita articles
        run: python fetch_qiita.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add qiita_articles.md
          git commit -m "Update Qiita articles"
          git push
